language: node_js
node_js:
- '0.10'
env:
  global:
  - secure: iyx4vQYRw+Jk0SHb/Hm122hs4BjP20O6+oCYVNpWDl7L/M6928PInH7x9V9COa5xu4VHE4YQLqT+/rq0o/C3zftCNHrqNaEcJnFKhEUcn5LM9lok09M9VNOuVo3Gb+zHRcSTmd08W/lx/ee0UHB58VKqMXoF2fca2M1NJhijhPY=
before_script: npm install -g grunt-cli
script: grunt ci
